---
title: "retrain_object_detector"
author: "GabiK"
date: '2022-06-25'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
```

Creates Figure 3: F1 scores vs number of images used for re-training per site (6 untrained locations)

```{r data}
dat_files=list.files(path="./detector_retrain_data/", pattern="\\.csv$",full.names = TRUE) 

df=map_df(dat_files, ~read_csv(.x) %>%
                 mutate(Site = str_sub(str_split(.x, pattern="/")[[1]][3],start=1, end=-5)))

head(df)
df$Site=gsub("Grube_Emma","Grube Emma",df$Site)
df$n=as.factor(df$n)
df$Site=as.factor(df$Site)
```

```{r plot}
# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

df %>% 
  ggplot(aes(x=n, y=F1, group=Site))+
  geom_line(aes(col=Site),size=0.8)+
  geom_point(aes(col=Site),size=2)+
  theme_bw()+
  labs(x="number of images used for retraining",
       y="F1-score (object detection)")+
  theme(legend.justification = c(1.04, 0), 
    legend.position = c(1.01, 0),
    legend.box.background = element_rect(colour = "black"),
    legend.title.align=0.5,
    aspect.ratio = 1)+
  scale_colour_manual(values=rev(cbbPalette))+
  scale_y_continuous(breaks = round(seq(min(df$F1), max(df$F1), by = 0.1),1))

ggsave(paste0("./output/F1_objectdet_retrain.png"),
       width =12, height =12, dpi = 800, units = "cm", device='png')
```

```{r increase_summary}
df %>% 
  filter(Site=="Calw")
df %>% 
  filter(n==0) 
df %>% 
  group_by(Site) %>% 
  summarise(minF=min(F1),
            maxF=max(F1),
            increase=maxF-minF)
```
